### ISSUE TITLE
Ошибка равертывания проекта

### ISSUE THREAD

**Issue by AlexandrBehunkov** [savushkin-r-d/ptusa-main-bin#1]
При развертывании проекта с использованием submodules получаю вот такую ошибку. Отсутствует папка exe с необходимыми файлами.
![image](https://user-images.githubusercontent.com/58733814/142575397-232c3044-b9d4-4851-b468-d59f78fed680.png)

**Comment by AlexandrBehunkov** [comment]
@idzm Нужно ваше мнение.

**Comment by idzm** [comment]
Нужно дополнительно установить модуль lfs.

**Comment by AlexandrBehunkov** [comment]
> Нужно дополнительно установить модуль lfs.

Хорошо, сделаю.

**Comment by idzm** [comment]
Вот что должно быть также установлено:

![изображение](https://user-images.githubusercontent.com/23375200/143059248-a054f9be-3044-415b-8d74-f11772b503cf.png)
